name: Stock Updater

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  refresh-data:
    runs-on: ubuntu-latest
    steps:
      - name: verify repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: start node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      - name: price sync
        run: node fetch-data.js 
        env:
          FINNHUB_TOKEN: ${{ secrets.FINNHUB_TOKEN }} 

      - name: commit the sync
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add stock-data.json
          
          # Check if the JSON file actually changed before committing
          if ! git diff-index --quiet HEAD; then
            git commit -m "[cron] synced baseline core vector datasets"
            
            # Pull any manual changes you made to the repo to prevent push conflicts
            git pull --rebase origin main 
            
            git push
              echo "update all good"
          else
            echo "no change detected"
          fi
